### ISSUE TITLE
PyPi release

### ISSUE THREAD

**Issue by bogdal** [jabbas/pynapi#1]
Hi @jabbas 

Could you release the current version of this package on PyPi?

**Comment by jabbas** [comment]
Surely, there is one bug to fix, it doesn't ignore directories and tries to
calc the hash from them, when I fix it I'll do the release on pypi. But in
the mean time you can always do: pip install git+
https://github.com/jabbas/pynapi.git

http://stackoverflow.com/questions/4830856/is-it-possible-to-use-pip-to-install-a-package-from-a-private-github-repository

sob., 15 sie 2015, 10:46 Adam Bogdał użytkownik notifications@github.com
napisał:

**Comment by jabbas** [comment]
```
Submitting dist/pynapi-0.5.1.tar.gz to https://pypi.python.org/pypi
Server response (200): OK
```

https://pypi.python.org/pypi/pynapi/0.5.1
Done and done! :) Thanks for helping me out!
