### ISSUE TITLE
Pynapi przestało działać

### ISSUE THREAD

**Issue by sledzik1984** [jabbas/pynapi#4]
Próba pobrania napisów kończy się ściągnięciem pliku którego zawartość to 
"Brak pliku tymczasowego"

**Comment by jabbas** [comment]
Niestety coś jest nie tak z serwerami napiprojekt... 

Taki sam błąd jakiś czas temu i odpowiedź ludzi z napiprojekt: http://forum.napiprojekt.pl/viewtopic.php?t=9589&view=previous&sid=5b5f8d069570e89ae9d1e8af3bf5d93e

**Comment by jabbas** [comment]
Stworzyłem poprawkę, która zwraca błąd (zamiast zapisywać "bzdury" do pliku z napisami) gdy taka sytuacja się pojawi.

Można zaktualizować przez pypi (https://pypi.python.org/pypi/pynapi/0.5.7) lub użyć tagu 0.5.7 na githubie

**Comment by jabbas** [comment]
Jeśli sytuacja się nie poprawi (napiprojekt nie naprawi serwerów - bądź okaże się, że to zamierzona sytuacja - będziemy myśleć co dalej) :)
